package CalculatorModule;


/**
* CalculatorModule/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorModule.idl
* Sunday, 28 April, 2024 9:54:46 PM IST
*/

public interface CalculatorOperations 
{
  double addition (double num1, double num2);
  double subtraction (double num1, double num2);
  double multiplication (double num1, double num2);
  double division (double num1, double num2);
} // interface CalculatorOperations
