package EvenModule;


/**
* EvenModule/EvenPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EvenModule.idl
* Sunday, 28 April, 2024 10:38:16 PM IST
*/

public abstract class EvenPOA extends org.omg.PortableServer.Servant
 implements EvenModule.EvenOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("oddeven", new java.lang.Integer (0));
    _methods.put ("prime", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // EvenModule/Even/oddeven
       {
         double num1 = in.read_double ();
         String $result = null;
         $result = this.oddeven (num1);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // EvenModule/Even/prime
       {
         double num2 = in.read_double ();
         String $result = null;
         $result = this.prime (num2);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:EvenModule/Even:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Even _this() 
  {
    return EvenHelper.narrow(
    super._this_object());
  }

  public Even _this(org.omg.CORBA.ORB orb) 
  {
    return EvenHelper.narrow(
    super._this_object(orb));
  }


} // class EvenPOA
