package EvenModule;


/**
* EvenModule/EvenOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EvenModule.idl
* Sunday, 28 April, 2024 10:38:16 PM IST
*/

public interface EvenOperations 
{
  String oddeven (double num1);
  String prime (double num2);
} // interface EvenOperations
