package EvenModule;


/**
* EvenModule/Even.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EvenModule.idl
* Sunday, 28 April, 2024 10:38:16 PM IST
*/

public interface Even extends EvenOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Even
